### PR TITLE
Integration with Silex2

### PR DESCRIPTION
**Pull request by rafaelnery**
The only question remains ...
As for the branch / project, these changes alter the functioning of the ServiceProviders Silex2, breaking compatibility with Silex1

### CODE REVIEW

**Comment by cristianoc72** [comment]
We should continue to support Silex 1, because it's still the stable version.
Imho we could split `2.x` branch into:
- 2.1 for Propel 2 - Silex 1
- 2.2 for Propel 2 -  Silex 2

What's your mind @marcj ?

**Comment by rafaelnery** [comment]
It would be ugly if ... so stay 2 providers, separated by namespace or filename?

But the dependencies would be different. Once the project would depend on silex 1 and 2 at the same time ...

:(

**Comment by marcj** [comment]
If there are two stable version then it makes sense to have two branches for each version. But I have no idea about Silex, so I'm out of this discussion :P

**Comment by rafaelnery** [comment]
I will make changes to the version 1.x Propel for Silex 2.
I think that it could be the same in both versions.

**Comment by cristianoc72** [comment]
The code in this PR is ok for me. 
Imho the best solution to maintain the compatibility with Silex 1 is to create another repository `PropelServiceProvider2` with the same branching model of `PropelServiceProvider`.
@marcj if you are agree, please could you create it?

**Comment by marcj** [comment]
Done :)

**Comment by rafaelnery** [comment]
Show!

But, I Can`t send a pull request in empty repository :)

**Comment by cristianoc72** [comment]
I've pulled your code and I'll push it into the new repository asap.
Il 18/gen/2016 12:05, "Rafael Nery" notifications@github.com ha scritto:

**Comment by rafaelnery** [comment]
OK! Tks!

**Pull request closed without merging**
